export const CAPTURE_EVENTS_BATCH_INTERVAL_MS = 250
export const NETWORK_REQUEST_TIMEOUT_MS = 5000
export const MAX_EVENT_PAYLOAD_SIZE_KB = 100

export const STORAGE_KEYS = {
  ACTIVE_SESSION_ID: 'active_session_id',
  RECORDING_STATE: 'recording_state'
} as const

export const MESSAGE_ACTIONS = {
  START_RECORDING: 'START_RECORDING',
  STOP_RECORDING: 'STOP_RECORDING',
  PAUSE_RECORDING: 'PAUSE_RECORDING',
  EVENT_BATCH: 'EVENT_BATCH',
  GET_STATUS: 'GET_STATUS'
} as const