import { useEffect } from 'react'
import { useThemeStore, initializeTheme } from '../store/themeStore'
import { useSettingsStore, initializeSettings } from '../store/settingsStore'
import * as Switch from '@radix-ui/react-switch'

export function Options() {
  const { theme, setTheme } = useThemeStore()
  const { defaultGenerationMode, filterAnalytics, setDefaultGenerationMode, setFilterAnalytics } = useSettingsStore()

  useEffect(() => {
    initializeTheme()
    initializeSettings()
  }, [])

  return (
    <div className="min-h-screen bg-background text-foreground p-8 flex justify-center">
      <div className="w-full max-w-2xl flex flex-col gap-8">
        <header className="border-b pb-4">
          <h1 className="text-2xl font-bold">AgentLens Settings</h1>
          <p className="text-foreground/60 mt-1">Configure your behavior capture preferences.</p>
        </header>

        {/* Appearance Section */}
        <section className="flex flex-col gap-4">
          <h2 className="text-lg font-semibold">Appearance</h2>
          <div className="flex items-center justify-between p-4 border border-border rounded-md">
            <div>
              <p className="text-sm font-medium">Theme</p>
              <p className="text-xs text-foreground/60">Select your preferred color scheme.</p>
            </div>
            <select
              value={theme}
              onChange={(e) => setTheme(e.target.value as 'light' | 'dark' | 'system')}
              className="bg-foreground/5 border border-border rounded-md px-3 py-1.5 text-sm focus:outline-none focus:ring-1 focus:ring-foreground"
            >
              <option value="system">System</option>
              <option value="light">Light</option>
              <option value="dark">Dark</option>
            </select>
          </div>
        </section>

        {/* Capture Section */}
        <section className="flex flex-col gap-4">
          <h2 className="text-lg font-semibold">Capture & Generation</h2>
          
          <div className="flex items-center justify-between p-4 border border-border rounded-md">
            <div>
              <p className="text-sm font-medium">Default Generation Mode</p>
              <p className="text-xs text-foreground/60">Choose how files are generated by default.</p>
            </div>
            <select
              value={defaultGenerationMode}
              onChange={(e) => setDefaultGenerationMode(e.target.value as 'raw' | 'enhanced')}
              className="bg-foreground/5 border border-border rounded-md px-3 py-1.5 text-sm focus:outline-none focus:ring-1 focus:ring-foreground"
            >
              <option value="raw">Raw (Deterministic)</option>
              <option value="enhanced">Enhanced (AI via OpenRouter)</option>
            </select>
          </div>

          <div className="flex items-center justify-between p-4 border border-border rounded-md">
            <div>
              <p className="text-sm font-medium">Filter Analytics Noise</p>
              <p className="text-xs text-foreground/60">Strip Google Analytics, Mixpanel, etc., from captured network events.</p>
            </div>
            <Switch.Root
              checked={filterAnalytics}
              onCheckedChange={setFilterAnalytics}
              className="relative h-[24px] w-[44px] rounded-full bg-foreground/20 data-[state=checked]:bg-primary transition-colors"
            >
              <Switch.Thumb className="block h-[18px] w-[18px] translate-x-[3px] rounded-full bg-white transition-transform data-[state=checked]:translate-x-[23px]" />
            </Switch.Root>
          </div>
        </section>

        {/* API Key Info */}
        <section className="flex flex-col gap-4">
          <h2 className="text-lg font-semibold">API Configuration</h2>
          <div className="p-4 border border-border rounded-md bg-foreground/5">
            <p className="text-sm text-foreground/80">
              The OpenRouter API key is loaded from your local environment (`.env`). 
              It is never stored in the database or sent to any third party other than OpenRouter directly.
            </p>
            <p className="text-xs text-foreground/50 mt-2 font-mono">
              Status: {process.env.PLASMO_PUBLIC_OPENROUTER_API_KEY ? '✅ Key Detected' : '❌ Key Missing'}
            </p>
          </div>
        </section>

      </div>
    </div>
  )
}